server:
  port: 8000
  forward-headers-strategy: framework
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: gustavo10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: cambio_service
    user: root
    password: gustavo10

springdoc:
  api-docs:
    path: cambio-service/v3/api-docs
  show-actuator: true
  swagger-ui:
    config-url: cambio-service/v3/api-docs/swagger-config
    url: cambio-service/v3/api-docs/**
    enabled: true